### ISSUE TITLE
Crash if the description exceeds 251 characters

### ISSUE THREAD

**Issue by ehamiter** [cbh123/charl-e#2]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
You should be able to enter a lengthy prompt, for example:

> powerful dark matter mancer, dark soul 3, Extra-Wide Angle, 3d zbrush, trend on ArtStation, Realistic Lighting, Volumetric Lighting, dramatic, 8k, cinematic, super detailed, vfx, symmetrical face and body, full body portrait, cinematic lighting, hyperdetailed, detailed realistic symmetrical eyes, cinematic lighting, hyperdetailed, cgsociety, 8k, high resolution, noah bradley, Billelis, masamune shirow, katsuhiro Otomo, insanely detailed and intricate, dark, dramatic, powerful, poster, cinematic Lighting through volume, Style=render, highly detail render with octane, octane render, color black and gold, photorealistic

and have the image generate.

## Current Behavior

Currently, the filename is saved as the description, with spaces replaced with dashes, and `.png` added to the suffix. If this filename exceeds 255 characters, the following error is thrown and the program halts:

```
OSError: [Errno 63] File name too long: '<filename here>[25502] Failed to execute script 'txt2img' due to unhandled exception!
```

## Steps to Reproduce

1. Enter a description greater than 251 characters
2. Generate

**Comment by cbh123** [comment]
Thanks! will fix this

**Comment by cbh123** [comment]
Fixed in latest!
